<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="L5Q15WJWVC" failures="1" tests="5" name="Surefire test" time="0.843" errors="0" timestamp="2025-04-08T01:27:05 CEST">
  <testcase classname="com.n26.UserTests" name="createUser_withValidData_shouldCreatedSuccessfully" time="0.614"/>
  <testcase classname="com.n26.UserTests" name="getUserDetail_ByValidUsername" time="0.029"/>
  <testcase classname="com.n26.UserTests" name="updateUserDetail_withValidData_shouldBeUpdatedSuccessfully" time="0.013"/>
  <testcase classname="com.n26.UserTests" name="deleteUser_withValidData_shouldBeDeletedSuccessfully" time="0.043"/>
  <testcase classname="com.n26.FailedUserTest" name="getUser_withInvalidData_errorInresponse" time="0.012">
    <failure type="java.lang.AssertionError" message="Actual value is 404 But Expected Value is : 200">
      <![CDATA[java.lang.AssertionError: Actual value is 404 But Expected Value is : 200
at com.n26.ApiActionsManager.RestAssuredActions.validateStatusCode(RestAssuredActions.java:143)
at com.n26.FailedUserTest.getUser_withInvalidData_errorInresponse(FailedUserTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getUser_withInvalidData_errorInresponse -->
</testsuite> <!-- Surefire test -->
